#mkdir $HOME/jupyter
#docker compose --file docker-compose-jupyter-datascience-notebook.yml up"
services:
  jupyter-datascience-notebook:
      image: quay.io/jupyter/datascience-notebook
      ports:
          - 8888:8888
      volumes:
          - type: bind
            source: ${HOME}/jupyter
            target: /home/jovyan/work
      environment:
          JUPYTER_ENABLE_LAB: "yes"
          JUPYTER_TOKEN: "go" # would effectively disable authentication by setting to an easy password like 0000 in this example
          GRANT_SUDO: "yes"
